# ДЗ

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import norm, t

#### 1) 
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): \
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], \
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].\
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array((35, 45, 190, 200, 40, 70, 54, 150, 120, 110))
ks = np.array((401, 574, 874, 919, 459, 739, 653, 902, 746, 832))

In [3]:
xy = zp*ks
M_xy = np.sum(xy)/(len(xy))
M_x = np.sum(zp)/(len(zp))
M_y = np.sum(ks)/(len(ks))
# ковариация, рассчитанная вручную
cov = M_xy - M_x*M_y
cov

9157.839999999997

In [4]:
# ковариация рассчитанная методом numpy
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [5]:
# смещенная sigma
sigma_x = np.sqrt(np.sum((zp - M_x)**2)/(len(zp)))
sigma_x 

59.115480206118605

In [6]:
sigma_y = np.sqrt(np.sum((ks - M_y)**2)/(len(ks)))
sigma_y

174.55340157098058

In [7]:
# корреляция, рассчитанная вручную
corr = cov/(sigma_x*sigma_y)
corr

0.8874900920739158

In [8]:
# корреляция, рассчитанная методом numpy
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

#### 2) 
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [9]:
X = np.array((131, 125, 115, 122, 131, 115, 107, 99, 125, 111))
X

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [27]:
a = 0.05
n = len(X)
mu = np.sum(X)/n
sigma = np.sqrt(np.sum((X-mu)**2)/(n-1))

print(f'Доверительный интервал с надежностью: 95% (alfa={a*100}%)')
print(f'Оценка мат ожидания Х: {mu:.4f}')
print(f'Несмещенная оценка СКО: {sigma:.4f}')
d = []
d.append(mu + t.ppf(a/2, n-1)*sigma/np.sqrt(n))
d.append(mu - t.ppf(a/2, n-1)*sigma/np.sqrt(n))
print(f'Доверительный интервал: {d}')

Доверительный интервал с надежностью: 95% (alfa=5.0%)
Оценка мат ожидания Х: 118.1000
Несмещенная оценка СКО: 10.5457
Доверительный интервал: [110.55608365158724, 125.64391634841274]


#### 3) 
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [28]:
a = 0.05
n = 27
D = 25
sigma = np.sqrt(D)
mu = 174.2
print(f'Доверительный интервал с надежностью: 95% (alfa={a*100}%)')
print(f'Оценка мат ожидания Х: {mu}')
print(f'Несмещенная оценка СКО: {sigma}')
d = []
d.append(mu + norm.ppf(a/2)*sigma/np.sqrt(n))
d.append(mu - norm.ppf(a/2)*sigma/np.sqrt(n))
print(f'Доверительный интервал: {d}')

Доверительный интервал с надежностью: 95% (alfa=5.0%)
Оценка мат ожидания Х: 174.2
Несмещенная оценка СКО: 5.0
Доверительный интервал: [172.3140237765397, 176.08597622346028]
